# FlexoTwin Smart Maintenance 4.0 - Docker Compose
# Multi-service deployment configuration

version: "3.8"

services:
  # ========================================
  # FlexoTwin API Service
  # ========================================
  flexotwin-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flexotwin-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      # Mount logs directory untuk persistent logging
      - ./logs:/app/logs
      # Mount data directory (read-only untuk security)
      - ./03_Data:/app/03_Data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - flexotwin-network

  # ========================================
  # Redis Cache (Optional - untuk scaling)
  # ========================================
  redis:
    image: redis:7-alpine
    container_name: flexotwin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - flexotwin-network
    command: redis-server --appendonly yes

  # ========================================
  # Nginx Reverse Proxy (Optional)
  # ========================================
  nginx:
    image: nginx:alpine
    container_name: flexotwin-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - flexotwin-api
    restart: unless-stopped
    networks:
      - flexotwin-network

  # ========================================
  # Monitoring (Optional - Prometheus)
  # ========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: flexotwin-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    restart: unless-stopped
    networks:
      - flexotwin-network

  # ========================================
  # Grafana Dashboard (Optional)
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: flexotwin-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - flexotwin-network

# ========================================
# Networks
# ========================================
networks:
  flexotwin-network:
    driver: bridge
    name: flexotwin-network

# ========================================
# Volumes
# ========================================
volumes:
  redis_data:
    name: flexotwin_redis_data
  prometheus_data:
    name: flexotwin_prometheus_data
  grafana_data:
    name: flexotwin_grafana_data
